export const GENERATE_REPORT = 'GENERATE_REPORT';
export const CLEAR_REPORT = 'CLEAR_REPORT';
export const SEARCH_NUGET = 'SEARCH_NUGET';
export const SEARCH_NUGET_PACKAGES = 'SEARCH_NUGET_PACKAGES';
